<% @LANGUAGE="VBSCRIPT" CODEPAGE="65001" %>
<% Response.ContentType="text/vnd.wap.wml; charset=utf-8" %>
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE wml PUBLIC "-//WAPFORUM//DTD WML 1.1//EN" "http://www.wapforum.org/DTD/wml_1.1.xml">
<wml>
<head>
<meta http-equiv="Cache-Control" content="max-age=0"/>
<meta http-equiv="Cache-Control" content="no-cache"/>
<meta http-equiv="Expires" content="Mon, 1 Jan 1990 00:00:00 GMT"/>
</head>
<card id="index" title="出售物品">  
<p align="left">
<anchor><prev/>[-返回-]</anchor><br/>
<%
wpid=request("wpid")
SessionID=request.querystring("SessionID")
if SessionID="" then SessionID=Session("SessionID")
if session("useid")="" then
       Session("returnuppath")=Request.ServerVariables("PATH_INFO") & "?wpid="&wpid&""
        response.redirect "/BBS/UseLogin.asp?SessionID="&SessionID&""
    End if
Server.ScriptTimeout=999
Select Case wpid
Case "wq" 
itidtit="木剑"
jiage="80"
danwei="把"
Case "hcj" 
itidtit="回城卷"
jiage="20"
danwei="个"
Case "w1" 
itidtit="光芒剑"
jiage="160"
danwei="把"
Case "w2" 
itidtit="战神剑"
jiage="400"
danwei="把"
Case "w3" 
itidtit="天使剑"
jiage="800"
danwei="把"
Case "w4" 
itidtit="黄金剑"
jiage="1300"
danwei="把"
Case "w5" 
itidtit="毁灭剑"
jiage="1900"
danwei="把"
Case "w6" 
itidtit="蝴蝶剑"
jiage="2500"
danwei="把"
Case "w7" 
itidtit="龙王剑"
jiage="8000"
danwei="把"
Case "w8" 
itidtit="轩辕煞魂斩"
jiage="100000"
danwei="把"
Case "dp" 
itidtit="布衣"
jiage="80"
danwei="件"
Case "d1" 
itidtit="光芒甲"
jiage="160"
danwei="件"
Case "d2" 
itidtit="战神甲"
jiage="300"
danwei="件"
Case "d3" 
itidtit="天使甲"
jiage="600"
danwei="件"
Case "d4" 
itidtit="黄金甲"
jiage="1000"
danwei="件"
Case "d5" 
itidtit="毁灭甲"
jiage="1500"
danwei="件"
Case "d6" 
itidtit="蝴蝶甲"
jiage="2100"
danwei="件"
Case "d7" 
itidtit="龙王甲"
jiage="8000"
danwei="件"
Case "d8" 
itidtit="轩辕圣甲"
jiage="100000"
danwei="件"
Case "kyaa" 
itidtit="布料靴"
jiage="80"
danwei="件"
Case "k1" 
itidtit="光芒靴"
jiage="120"
danwei="件"
Case "k2" 
itidtit="战神靴"
jiage="300"
danwei="件"
Case "k3" 
itidtit="天使靴"
jiage="600"
danwei="件"
Case "k4" 
itidtit="黄金靴"
jiage="1000"
danwei="件"
Case "k5" 
itidtit="毁灭靴"
jiage="1500"
danwei="件"
Case "k6" 
itidtit="蝴蝶靴"
jiage="2100"
danwei="件"
Case "k7" 
itidtit="龙王靴"
jiage="8000"
danwei="件"
Case "k8" 
itidtit="轩辕圣靴"
jiage="100000"
danwei="件"
Case "tou" 
itidtit="布料头盔"
jiage="80"
danwei="件"
Case "t1" 
itidtit="光芒头盔"
jiage="120"
danwei="件"
Case "t2" 
itidtit="战神头盔"
jiage="300"
danwei="件"
Case "t3" 
itidtit="天使头盔"
jiage="600"
danwei="件"
Case "t4" 
itidtit="黄金头盔"
jiage="1000"
danwei="件"
Case "t5" 
itidtit="毁灭头盔"
jiage="1500"
danwei="件"
Case "t6" 
itidtit="蝴蝶头盔"
jiage="2100"
danwei="件"
Case "t7" 
itidtit="龙王头盔"
jiage="8000"
danwei="件"
Case "t8" 
itidtit="轩辕圣盔"
jiage="100000"
danwei="件"
Case "y1" 
itidtit="百草丹"
jiage="20"
danwei="颗"
Case "y2" 
itidtit="大力神丹"
jiage="160"
danwei="颗"
Case "y3" 
itidtit="九转还魂丹"
jiage="400"
danwei="颗"
Case "y4" 
itidtit="少林大还丹"
jiage="800"
danwei="颗"
Case "y5" 
itidtit="江湖强力魔水"
jiage="80000"
danwei="颗"
Case "y6" 
itidtit="情人花"
jiage="80000"
danwei="朵"
Case "bs" 
itidtit="宝石"
danwei="颗"
jiage="80000"
Case "h1"
     itidtit="小虾"
danwei="条"
jiage="80"
   Case "h2"
     itidtit="鲤鱼"
danwei="条"
jiage="160"
   Case "h3"
     itidtit="螃蟹"
danwei="只"
jiage="300"
   Case "h4"
     itidtit="大水鱼"
danwei="只"
jiage="500"
   Case "j1"
     itidtit="锡"
danwei="块"
jiage="80"
   Case "j2"
     itidtit="铜"
danwei="块"
jiage="160"
   Case "j3"
     itidtit="银"
danwei="块"
jiage="240"
   Case "j4"
     itidtit="金"
danwei="块"
jiage="480"
Case "ml" 
itidtit="木料"
jiage="20"
danwei="棵"
 End Select

Response.Write "陈六对您说：<br/>物品:<u>" & itidtit & "</u><br/>回收价格:<b><u>" & jiage & "</u></b>两/" & danwei & "<br/>这位少侠，请问您要卖多少" & danwei & "？<br/>"
%>
<img src='1.gif' alt='------------'/><br/>
你说：<br/>我要卖:<input name="num" size="3" format="*N"/><%=danwei%>
<br/>
<anchor>看看共值多少银两
<go method="post" href="dan1.asp?SessionID=<%=SessionID%>">
<postfield name="did" value="<%=wpid%>"/>
<postfield name="num" value="$(num)"/>
</go></anchor><br/>
------------<br/>
<a href="/bbs/yxxe/index.asp?SessionID=<%=SessionID%>">江湖首页</a><br/>
<a href="/bbs/index.asp?SessionID=<%=SessionID%>">社区首页</a>
</p>
</card>
</wml>
