<%
  Select Case itid
 Case "1"
      itidtit="贴图专区"
 Case "2" 
      itidtit="影音游戏"
 Case "3" 
      itidtit="游戏地带"
 Case "4"
      itidtit="精彩视频"
 Case "5"
      itidtit="动漫专区"
 Case "6"
      itidtit="短文故乡"
 Case "7"
      itidtit="谈情解爱"
 Case "8"
      itidtit="散文天下"
 Case "9"
      itidtit="职场天地"
 Case "10"
      itidtit="三十不嫁"
 Case "11"
      itidtit="爆笑乐园"
 Case "12"
      itidtit="灌水专区"
 Case "13"
      itidtit="交友婚约"
 Case "14"
      itidtit="ＩＴ视界"
 Case "15"
      itidtit="女系氏族"
 Case "16"
      itidtit="传媒江湖"
 Case "17"
      itidtit="舞文弄墨"
 Case "18"
      itidtit="电脑网络"
 Case "19"
      itidtit="关天茶舍"
 Case "20"
      itidtit="经济论坛"
 Case "21"
      itidtit="闲闲书话"
 Case "22"
      itidtit="网罗天下"
   Case "23"
      itidtit="仗剑天涯"
   Case "24"
      itidtit="怪力乱论"
   Case "25"
      itidtit="煮酒论史"
   Case "26"
      itidtit="热血军团"
   Case "27"
      itidtit="一路同行"
   Case "28"
      itidtit="管理前线"
   Case "29"
      itidtit="求歌资询"
   Case "30"
      itidtit="心灵热线"
   Case "31" 
      itidtit="奇思妙想"
   Case "32" 
      itidtit="国际观察"
   Case "33"
      itidtit="理财赢家"
   Case "34"
      itidtit="议事广场"
   Case "35"
      itidtit="股市论谈"
   Case "36"
      itidtit="篮球公园"
   Case "37"
      itidtit="公仆在线"
   Case "38"
      itidtit="文学交流"
   Case "39"
      itidtit="狂野杂谈"
   Case "40"
      itidtit="青春地图"
   Case "41"
      itidtit="旅游休闲"
   Case "42"
      itidtit="球迷一家"
   Case "43"
      itidtit="汽车时代"
   Case "44"
      itidtit="体育聚焦"
   Case "45"
      itidtit="时尚资讯"
   Case "46"
      itidtit="手机数码"
   Case "47"
      itidtit="法律论坛"
   Case "48"
      itidtit="影视评论"
   Case "49"
      itidtit="我的大学"
   Case "50"
      itidtit="娱乐八卦"
   Case "51"
      itidtit="狂野医院"
   Case "52"
      itidtit="蓦然回首"
   Case "53"
      itidtit="旧爱新欢"
   Case "54"
      itidtit="都市生活"
   Case "55"
      itidtit="生肖血型"
   Case "56" 
      itidtit="对联雅座"
   Case "57" 
      itidtit="光棍一族"
   Case "58"
      itidtit="深夜孤独"
   Case "59"
      itidtit="男左女右"
  Case "60"
      itidtit="双子座"
  Case "61"
      itidtit="双鱼座" 
   Case "62"
      itidtit="水瓶座"
   Case "63"
      itidtit="摩羯座"
   Case "64"
      itidtit="射手座"
   Case "65"
      itidtit="天蝎座"
   Case "66"
      itidtit="天秤座"
   Case "67"
      itidtit="处女座"
   Case "68"
      itidtit="狮子座"
   Case "69"
      itidtit="巨蟹座"
   Case "70"
      itidtit="金牛座"
   Case "71"
      itidtit="白羊座"
   Case "72"
      itidtit="待审"
   Case "73"
      itidtit="待审"
   Case "74"
      itidtit="客服建议"
   Case "75"
      itidtit="待审"
   Case "76"
      itidtit="待审"
   Case "77" 
      itidtit="家园公告"
   Case "78"
      itidtit="公共聊吧"
   Case "79"
      itidtit="社区客服"
   Case "80"
      itidtit="版主交流"
  Case "81"
      itidtit="社区活动"
   Case "82"
      itidtit="新手乐园"
   Case "83"
      itidtit="站长推荐"
   Case "84"
      itidtit="成人贴图"
   Case "85"
      itidtit="激情小说"
   Case "86"
      itidtit="高清大图"
   Case "87"
      itidtit="成人视频"
   Case "88"
      itidtit="吉林论坛"
   Case "89"
      itidtit="陕西论坛"
   Case "90"
      itidtit="儋州论坛"
   Case "91"
      itidtit="贵州论坛"
   Case "92"
      itidtit="柳州论坛"
   Case "93"
      itidtit="武汉论坛"
   Case "94"
      itidtit="昆明论坛"
   Case "95"
      itidtit="青岛论坛"
   Case "96"
      itidtit="南京论坛"
   Case "97"
      itidtit="拉萨论坛"
   Case "98"
      itidtit="西安论坛"
   Case "99"
      itidtit="深圳论坛"
 Case "100"
      itidtit="北京论坛"
 Case "101"
      itidtit="重庆论坛"
 Case "102"
      itidtit="上海论坛"
 Case "103"
      itidtit="天津论坛"
 Case "104"
      itidtit="四川论坛"
 Case "105"
      itidtit="广东论坛"
 Case "106"
      itidtit="广西论坛"
 Case "107"
      itidtit="河北论坛"
 Case "108"
      itidtit="河南论坛"
 Case "109"
      itidtit="云南论坛"
 Case "110"
      itidtit="安徽论坛"
 Case "111"
      itidtit="江西论坛"
 Case "112"
      itidtit="湖北论坛"
 Case "113"
      itidtit="湖南论坛"
 Case "114"
      itidtit="甘肃论坛"
 Case "115"
      itidtit="宁夏论坛"
 Case "116"
      itidtit="西藏论坛"
 Case "117"
      itidtit="福建论坛"
 Case "118"
      itidtit="辽宁论坛"
 Case "119"
      itidtit="山西论坛"
 Case "120"
      itidtit="吉林论坛"
 Case "121"
      itidtit="江苏论坛"
 Case "122"
      itidtit="浙江论坛"
 Case "123"
      itidtit="山东论坛"
 Case "124"
      itidtit="温州论坛"
 Case "125"
      itidtit="香港论坛"
 Case "126"
      itidtit="其他城市论坛"
End Select
%>